version: '3.4'

networks:
  default:
    external:
      name: demonet

services:
  sandwichmaker:
    image: sandwichmaker
    build:
      context: .
      dockerfile: SandwichMaker/Dockerfile
    environment: 
      - RABBITMQ__URL=rabbitsandwich
      - RABBITMQ__USER
      - RABBITMQ__PASSWORD

  gateway:
    image: gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    environment: 
      - RABBITMQ__URL=rabbitsandwich
      - RABBITMQ__USER
      - RABBITMQ__PASSWORD

  meatservice:
    image: meatservice
    build:
      context: .
      dockerfile: MeatService/Dockerfile
    environment: 
      - RABBITMQ__URL=rabbitsandwich
      - RABBITMQ__USER
      - RABBITMQ__PASSWORD

  breadservice:
    image: breadservice
    build:
      context: .
      dockerfile: BreadService/Dockerfile
    environment: 
      - RABBITMQ__URL=rabbitsandwich
      - RABBITMQ__USER
      - RABBITMQ__PASSWORD

  cheeseservice:
    image: cheeseservice
    build:
      context: .
      dockerfile: CheeseService/Dockerfile
    environment: 
      - RABBITMQ__URL=rabbitsandwich
      - RABBITMQ__USER
      - RABBITMQ__PASSWORD

  lettuceservice:
    image: lettuceservice
    build:
      context: .
      dockerfile: LettuceService/Dockerfile
    environment: 
      - RABBITMQ__URL=rabbitsandwich
      - RABBITMQ__USER
      - RABBITMQ__PASSWORD

